version = 1

test_patterns = ["**/**_test.py"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "monkey/monkey_island/requirements.txt",
  "monkey/infection_monkey/requirements.txt"
  ]

  [analyzers.meta]
  runtime_version = "3.x.x"
