blank_issues_enabled: false
contact_links:
  - name: Slack Channel
    url: https://join.slack.com/t/infectionmonkey/shared_invite/enQtNDU5MjAxMjg1MjU1LWM0NjVmNWE2ZTMzYzAxOWJiYmMxMzU0NWU3NmUxYjcyNjk0YWY2MDkwODk4NGMyNDU4NzA4MDljOWNmZWViNDU
    about: Our community Slack channel - you can ask questions or suggest things here.
  - name: FAQs
    url: https://www.guardicore.com/infectionmonkey/docs/faq/
    about: Frequently Asked Questions - if you have a question, see if we've already answered it!
